# Generated by Django 5.1.6 on 2025-02-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.IntegerField(max_length=14),
        ),
    ]
