# Generated by Django 5.1.6 on 2025-02-20 12:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_supplier_contact_alter_supplier_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'O campo deve conter exatamente 11 dígitos numéricos')]),
        ),
    ]
