# Generated by Django 5.1.6 on 2025-02-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_supplier_tax_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
