# Generated by Django 5.1.6 on 2025-02-08 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsible person'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='property',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='property',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.supplier', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='contract',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.property'),
        ),
    ]
