# Generated by Django 5.1.6 on 2025-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='quantity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
    ]
