# Generated by Django 5.1.6 on 2025-02-08 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('destination_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_movements', to='assets.department')),
                ('origin_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_movements', to='assets.department')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.property')),
            ],
        ),
    ]
