# Generated by Django 5.1.6 on 2025-02-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Maintenance', 'In Maintenance'), ('Completed', 'Completed')], default='Scheduled', max_length=50),
        ),
    ]
