# Generated by Django 5.1.6 on 2025-02-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Maintenance', 'In Maintenance'), ('Completed', 'Completed')], default='Agendado', max_length=50),
        ),
    ]
