# Generated by Django 5.1.6 on 2025-02-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_alter_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Agendado', 'Agendado'), ('Em Manutenção', 'Em Manutenção'), ('Completado', 'Completado')], default='Agendado', max_length=50),
        ),
    ]
